### ISSUE TITLE
WriteDirectory overflowing int on really big images

### ISSUE THREAD

**Issue by devedse** [BitMiracle/libtiff.net#15]
Hello,

I'm using your library to create enormous images. However when using the library to save an image of the following size I encounter some overflows when the directory is written to the file:
Width: 1048576
Height: 1048576
TileSize: 64x64

SizeOf(ulong): 8

In the WriteDirectory method (and submethods) a lot of BlockCopies are done (could probably also be optimized to reduce the memory footprint). BlockCopies work on byte level though so this means that when we have a total number of tiles of: (1048576 / 64) * (1048576 / 64) = 268435456. And we then multiply this number by the size of ulong to get the total amount of bytes we get a total of 2147483648 bytes. This happens to be just over int.MaxValue which results in the following exception being thrown:
30-10-2015   05:30:17:    System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at BitMiracle.LibTiff.Classic.Tiff.writeDirectory(Boolean done) in D:\The folder\Github\DeveMazeGenerator\LibTiff\LibTiff\Internal\Tiff_DirWrite.cs:line 206
   at BitMiracle.LibTiff.Classic.Tiff.Flush() in D:\The folder\Github\DeveMazeGenerator\LibTiff\LibTiff\Tiff.cs:line 767
   at BitMiracle.LibTiff.Classic.Tiff.Close() in D:\The folder\Github\DeveMazeGenerator\LibTiff\LibTiff\Tiff.cs:line 495
   at BitMiracle.LibTiff.Classic.Tiff.Dispose(Boolean disposing) in D:\The folder\Github\DeveMazeGenerator\LibTiff\LibTiff\Internal\Tiff_Internal.cs:line 326
   at BitMiracle.LibTiff.Classic.Tiff.Dispose() in D:\The folder\Github\DeveMazeGenerator\LibTiff\LibTiff\Tiff.cs:line 514
   at DeveMazeGenerator.Maze.Testje(Int32 size, Action`2 lineSavingProgress, Int32 tiffTileSize, Boolean useComplexImage, Action`1 debugMessageCallback) in D:\The folder\Github\DeveMazeGenerator\DeveMazeGenerator\Maze.SavingDeluxeTiff.cs:line 1016
   at DeveMazeGeneratorGui.Form1.<>c__DisplayClass75_0.<button45_Click>b__0() in D:\The folder\Github\DeveMazeGenerator\DeveMazeGeneratorGui\Form1.cs:line 2235

Is this something that can be resolved? (e.g. by replacing the BlockCopies by something that will keep processing them as long arrays and somehow write that to the file directly). Or maybe even writing the directory directly after writing the tile? (To also save memory on storing all locations of tiles).

Thanks all for the amazing work :),

Devedse

**Comment by Milster** [comment]
As far as I can remember the same issue will be encountered when you try to write 2+GB in a single strip. I would assume even creating the ulong[268435456] - array should throw an outofmemory exception.

I can't provide a fix, but using a larger TileSize, if it's possibly for you, will be a workaround for you.

**Comment by devedse** [comment]
The issue I had with larger tile sizes is that other software (e.g. Libvips) is running out of memory :| :
http://stackoverflow.com/questions/33357627/libvips-crashing-when-processing-3-9gb-tiff-image

But is there not a way where you can dynamically write the tile position buffer into the file? (Without having to keep it in memory).

**Comment by Milster** [comment]
Did you try a reasonable TileSize like 256 or 512? 4096x4096 seems very large, 64 is quite small.

**Comment by devedse** [comment]
I did indeed try bigger sizes but due to the internal workings of other libraries they have to load 2 rows of tiles to be able to process an image. And since the rows are so wide I already ran into issues using a tile size of 128.

**Comment by Bobrovsky** [comment]
@devedse Unfortunately, there is not much can be done here. As @Milster already pointed out, the library won't be able to allocate that large array of ulongs. 

The library probably can be changed to use much less memory when processing large images (and such a change is desirable). Please note that the change will probably take long time and will require many changes throughout the library's code. We don't have plans to implement the change in foreseeable future.
